const cardsMassiveWoman = [
  {
    image1: "./images/Slider_girls/w-hoodi-1.jpg",
    image2: "./images/Slider_girls/w-hoodi-2.jpg",
    image3: "./images/Slider_girls/w-hoodi-3.jpg",
    image4: "./images/Slider_girls/w-hoodi-4.jpg",
    title: "Костюм с худи",
    description: "Худи и штаны в цвете «капучино», базовая белая футболка",
    price: "4 650 руб",
  },
  {
    image1: "./images/Slider_girls/w-shot-1.jpg",
    image2: "./images/Slider_girls/w-shot-2.jpg",
    image3: "./images/Slider_girls/w-shot-3.jpg",
    image4: "./images/Slider_girls/w-shot-4.jpg",
    title: "Костюм со свитшотом",
    description: "Свитшот и штаны в цвете «капучино», базовая белая футболка",
    price: "4 150 руб",
  },
];

const cardsMassiveMen = [
  {
    image1: "./images/Slider_boys/m-hoodi-1.jpg",
    image2: "./images/Slider_boys/m-hoodi-2.jpg",
    image3: "./images/Slider_boys/m-hoodi-3.jpg",
    image4: "./images/Slider_boys/m-hoodi-4.jpg",
    title: "Костюм с худи",
    description: "Худи и штаны в цвете «капучино», базовая белая футболка",
    price: "4 650 руб",
    sizeZero: "XS",
    sizeFirst: "S",
    sizeSecond: "M",
    sizeThird: "L",
    sizeFourth: "XL",
  },
  {
    image1: "./images/Slider_boys/m-shot-1.jpg",
    image2: "./images/Slider_boys/m-shot-2.jpg",
    image3: "./images/Slider_boys/m-shot-3.jpg",
    image4: "./images/Slider_boys/m-shot-4.jpg",
    title: "Костюм со свитшотом",
    description: "Свитшот и штаны в цвете «капучино», базовая белая футболка",
    price: "4 150 руб",
    sizeFirst: "S",
    sizeSecond: "M",
    sizeThird: "L",
    sizeFourth: "XL",
  },
];
